### ISSUE TITLE
Establishing SignalR with angular cli proxy?

### ISSUE THREAD

**Issue by Mds92** [Ibro/SignalRSimpleChat#1]
I want to change the following line 
`this._hubConnection = new HubConnection('http://localhost:5000/chat');`
as
`this._hubConnection = new HubConnection('/chat');`
I want to set proxy for angular cli, Do you know how we can do it? without writing absolute address?
I did it and I get this error!
https://stackoverflow.com/questions/47852633/angular-5-1-1-infinite-refresh-loop-after-set-proxy-for-signalr

**Comment by Ibro** [comment]
I saw you resolved this.  :)

> Finally I could find the solution
> I have to change proxy config as follows:
> 
> const PROXY_CONFIG = [
>   {
>     context: [
>       "/api",
>       "/Temp",
>       "/Upload",
>       "/notificationHub"
>     ],
>     target: "http://localhost:52918/",
>     secure: false,
>     logLevel: 'debug',
>     ws: true
>   }
> ];
> It's OK now

**Comment by JanneHarju** [comment]
I did have problem where first connection take long time and then first retry time it started work. I added that **ws: true** to proxy config and it helped.
